"""v2.0 add color to department

Revision ID: 1d800d1e1274
Revises: 9a92946d4d71
Create Date: 2026-02-22 15:08:17.517553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d800d1e1274'
down_revision: Union[str, Sequence[str], None] = '9a92946d4d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('color', sa.String(length=7), server_default='#3B82F6', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'color')
    # ### end Alembic commands ###
