"""add appointments table with relationships

Revision ID: 35ef602b9cbb
Revises: 46798110e3cd
Create Date: 2026-02-04 14:43:40.111502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ef602b9cbb'
down_revision: Union[str, Sequence[str], None] = '46798110e3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la cita'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='ID del servicio'),
    sa.Column('collaborator_id', sa.Integer(), nullable=False, comment='ID del colaborador'),
    sa.Column('client_name', sa.String(length=100), nullable=False, comment='Nombre completo del cliente'),
    sa.Column('client_phone', sa.String(length=20), nullable=True, comment='Teléfono de contacto del cliente'),
    sa.Column('client_email', sa.String(length=255), nullable=True, comment='Email del cliente (opcional)'),
    sa.Column('client_notes', sa.Text(), nullable=True, comment='Notas adicionales del cliente'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de inicio'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de fin'),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'), nullable=False, comment='Estado actual de la cita'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
