"""add collaborators table

Revision ID: 46798110e3cd
Revises: 75f00c3736a9
Create Date: 2026-02-04 14:00:43.351913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46798110e3cd'
down_revision: Union[str, Sequence[str], None] = '75f00c3736a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único del colaborador'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre completo del colaborador'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email de contacto del colaborador'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica si el colaborador está activo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborators_email'), 'collaborators', ['email'], unique=False)
    op.create_index(op.f('ix_collaborators_id'), 'collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_collaborators_name'), 'collaborators', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaborators_name'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_id'), table_name='collaborators')
    op.drop_index(op.f('ix_collaborators_email'), table_name='collaborators')
    op.drop_table('collaborators')
    # ### end Alembic commands ###
