"""v1 crear_estructura_departamentos

Revision ID: 904287de2c05
Revises: 91010f9263ed
Create Date: 2026-02-14 16:15:57.225927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '904287de2c05'
down_revision: Union[str, Sequence[str], None] = '91010f9263ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Crear las tablas de departamentos primero
    op.create_table('departments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    
    op.create_table('collaborator_departments',
        sa.Column('collaborator_id', sa.Integer(), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['collaborator_id'], ['collaborators.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('collaborator_id', 'department_id')
    )

    # --- AQUÍ VIENE EL TRUCO PARA LOS SERVICIOS EXISTENTES ---

    # 2. Insertamos un departamento por defecto directamente vía SQL para que tenga el ID 1
    op.execute("INSERT INTO departments (id, name, is_active) VALUES (1, 'General', true) ON CONFLICT DO NOTHING")

    # 3. Añadimos la columna department_id pero permitiendo NULL temporalmente
    op.add_column('services', sa.Column('department_id', sa.Integer(), nullable=True))

    # 4. Asignamos todos los servicios actuales al departamento 1 (General)
    op.execute("UPDATE services SET department_id = 1")

    # 5. Ahora que todos tienen valor, ponemos la columna como NOT NULL
    op.alter_column('services', 'department_id', nullable=False)

    # 6. Finalmente añadimos la llave foránea
    op.create_foreign_key(None, 'services', 'departments', ['department_id'], ['id'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de última actualización',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de creación',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indica si el servicio está activo',
               existing_nullable=False)
    op.alter_column('services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Precio del servicio',
               existing_nullable=False)
    op.alter_column('services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               comment='Duración del servicio en minutos',
               existing_nullable=False)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre descriptivo del servicio',
               existing_nullable=False)
    op.alter_column('services', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único del servicio',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('services', 'department_id')
    op.alter_column('collaborators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de creación',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('collaborators', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indica si el colaborador está activo',
               existing_nullable=False)
    op.alter_column('collaborators', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email de contacto del colaborador',
               existing_nullable=True)
    op.alter_column('collaborators', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre completo del colaborador',
               existing_nullable=False)
    op.alter_column('collaborators', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único del colaborador',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('collaborator_departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
