"""crear_tabla_aprendizaje_final

Revision ID: 91010f9263ed
Revises: 9c76e0f02ae6
Create Date: 2026-02-14 14:50:55.575590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91010f9263ed'
down_revision: Union[str, Sequence[str], None] = '9c76e0f02ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_learning_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('module_name', sa.String(length=50), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_learning_logs_id'), 'ai_learning_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_learning_logs_phone'), 'ai_learning_logs', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_learning_logs_phone'), table_name='ai_learning_logs')
    op.drop_index(op.f('ix_ai_learning_logs_id'), table_name='ai_learning_logs')
    op.drop_table('ai_learning_logs')
    # ### end Alembic commands ###
