"""v2_crear tabla auditoria

Revision ID: 9a92946d4d71
Revises: 904287de2c05
Create Date: 2026-02-19 09:49:01.208719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a92946d4d71'
down_revision: Union[str, Sequence[str], None] = '904287de2c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único de la cita',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del cliente vinculado',
               existing_nullable=True)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del servicio',
               existing_nullable=False)
    op.alter_column('appointments', 'collaborator_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del colaborador',
               existing_nullable=False)
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nombre completo del cliente',
               existing_nullable=False)
    op.alter_column('appointments', 'client_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Teléfono de contacto del cliente',
               existing_nullable=True)
    op.alter_column('appointments', 'client_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email del cliente (opcional)',
               existing_nullable=True)
    op.alter_column('appointments', 'client_notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Notas adicionales del cliente',
               existing_nullable=True)
    op.alter_column('appointments', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               comment='Origen: ia, manual o web',
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('appointments', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de inicio',
               existing_nullable=False)
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha y hora de fin',
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'),
               comment=None,
               existing_comment='Estado actual de la cita',
               existing_nullable=False)
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de creación',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de última actualización',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('clients', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('clients_current_service_id_fkey'), 'clients', type_='foreignkey')
    op.alter_column('collaborators', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único del colaborador',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('collaborators', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nombre completo del colaborador',
               existing_nullable=False)
    op.alter_column('collaborators', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email de contacto del colaborador',
               existing_nullable=True)
    op.alter_column('collaborators', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica si el colaborador está activo',
               existing_nullable=False)
    op.alter_column('collaborators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de creación',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Identificador único del servicio',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nombre descriptivo del servicio',
               existing_nullable=False)
    op.alter_column('services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Duración del servicio en minutos',
               existing_nullable=False)
    op.alter_column('services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Precio del servicio',
               existing_nullable=False)
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica si el servicio está activo',
               existing_nullable=False)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de creación',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de última actualización',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de última actualización',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de creación',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indica si el servicio está activo',
               existing_nullable=False)
    op.alter_column('services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Precio del servicio',
               existing_nullable=False)
    op.alter_column('services', 'duration_minutes',
               existing_type=sa.INTEGER(),
               comment='Duración del servicio en minutos',
               existing_nullable=False)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre descriptivo del servicio',
               existing_nullable=False)
    op.alter_column('services', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único del servicio',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('collaborators', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de creación',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('collaborators', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Indica si el colaborador está activo',
               existing_nullable=False)
    op.alter_column('collaborators', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email de contacto del colaborador',
               existing_nullable=True)
    op.alter_column('collaborators', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre completo del colaborador',
               existing_nullable=False)
    op.alter_column('collaborators', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único del colaborador',
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(op.f('clients_current_service_id_fkey'), 'clients', 'services', ['current_service_id'], ['id'])
    op.alter_column('clients', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('clients', 'business_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('appointments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de última actualización',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de creación',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatus'),
               comment='Estado actual de la cita',
               existing_nullable=False)
    op.alter_column('appointments', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de fin',
               existing_nullable=False)
    op.alter_column('appointments', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de inicio',
               existing_nullable=False)
    op.alter_column('appointments', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               comment=None,
               existing_comment='Origen: ia, manual o web',
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('appointments', 'client_notes',
               existing_type=sa.TEXT(),
               comment='Notas adicionales del cliente',
               existing_nullable=True)
    op.alter_column('appointments', 'client_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email del cliente (opcional)',
               existing_nullable=True)
    op.alter_column('appointments', 'client_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='Teléfono de contacto del cliente',
               existing_nullable=True)
    op.alter_column('appointments', 'client_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nombre completo del cliente',
               existing_nullable=False)
    op.alter_column('appointments', 'collaborator_id',
               existing_type=sa.INTEGER(),
               comment='ID del colaborador',
               existing_nullable=False)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.INTEGER(),
               comment='ID del servicio',
               existing_nullable=False)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.INTEGER(),
               comment='ID del cliente vinculado',
               existing_nullable=True)
    op.alter_column('appointments', 'id',
               existing_type=sa.INTEGER(),
               comment='Identificador único de la cita',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
