"""create services and business hours tables

Revision ID: 9b48c6eeca83
Revises: 
Create Date: 2026-02-04 09:08:30.285352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b48c6eeca83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único de la configuración de horario'),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='Día de la semana (0=Lunes, 6=Domingo)'),
    sa.Column('day_name', sa.String(length=20), nullable=False, comment='Nombre del día (Lunes, Martes, etc.)'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='Indica si el día está habilitado para trabajo'),
    sa.Column('is_split_shift', sa.Boolean(), nullable=False, comment='Indica si el día tiene turno partido'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week')
    )
    op.create_index(op.f('ix_business_hours_id'), 'business_hours', ['id'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único del servicio'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nombre descriptivo del servicio'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='Duración del servicio en minutos'),
    sa.Column('price', sa.Float(), nullable=False, comment='Precio del servicio'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indica si el servicio está activo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único del slot de tiempo'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Hora de inicio del slot'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Hora de fin del slot'),
    sa.Column('slot_order', sa.Integer(), nullable=False, comment='Orden del slot (1=primero, 2=segundo)'),
    sa.Column('business_hours_id', sa.Integer(), nullable=False, comment='ID del día de la semana asociado'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de creación'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['business_hours_id'], ['business_hours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_slots_id'), 'time_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_slots_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_business_hours_id'), table_name='business_hours')
    op.drop_table('business_hours')
    # ### end Alembic commands ###
